version: "3.7"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
    image: api:adonis-4.1-dev
    ports:
      - 80:${PORT}
    volumes:
      - api_node_modules:/api/node_modules
      - ./.env:/api/.env
      - ./api:/api
    depends_on:
      - db
    command: bash -c "yarn install && yarn migrate && yarn start:dev"

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 92:80
    volumes:
      - pgadmin:/var/lib/pgadmin:delegated
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  api_node_modules:
