version: "3.7"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
    image: api:adonis-4.1-dev
    ports:
      - 80:${PORT}
    volumes:
      - api_node_modules:/api/node_modules
      - ./.env:/api/.env
      - ./api:/api
    depends_on:
      - db
    command: bash -c "yarn install && yarn migrate && yarn start:dev"

  db:
    build: ./docker/postgresql/
    image: api:db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      # - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:${DB_PORT}
    volumes:
      - db_volume:/var/lib/postgresql/data:delegated
      - ./docker/postgresql:/home:delegated

  db_log:
    build:
      context: ./docker/mongo/
      dockerfile: Dockerfile
      args:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_NAME=${MONGO_NAME}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
    image: api:mongo-0.1
    restart: always
    volumes:
      - log_volume:/data/db
      - ./docker/postgresql:/home:delegated
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 92:80
    volumes:
      - pgadmin:/var/lib/pgadmin:delegated
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  pgadmin:
  api_node_modules:
  db_volume:
  log_volume:
